# Generated by Django 4.1.2 on 2022-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_employee_role_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('swipe_in', models.DateTimeField()),
                ('swipe_out', models.DateTimeField()),
                ('total_hours', models.IntegerField()),
                ('full_or_half_day', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('leave_type', models.CharField(max_length=30)),
                ('leave_request_date', models.DateField()),
                ('leave_request_from', models.DateField()),
                ('leave_request_to', models.DateField()),
                ('leave_request_status', models.CharField(max_length=30)),
                ('leave_request_approved_by', models.CharField(max_length=30)),
            ],
        ),
    ]
