# Generated by Django 4.1.2 on 2022-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empattendancedetails_empleavedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('team_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
            ],
        ),
    ]
